{% set name = "bioat" %}
{% set version = "0.15.4" %}

package:
  name: {{ name|lower }}
  version: "0.15.4"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bioat-{{ version }}.tar.gz
  sha256: "7b7828e0025367a19edcad225f296ba1dd4bdf10b9c80278f696ecaa96052ef9"

build:
  entry_points:
    - bioat = bioat.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<3.13.0
    - pandas >=1.5
    - numpy >=1.24.1
    - tqdm >=4.64.1
    - fire >=0.5.0
    - biopython >=1.80
    - matplotlib-base >=3.5.3
    - tabulate >=0.9.0
    - statsmodels >=0.13.5
    - requests >=2.31.0
    - coloredlogs >=15.0.1
    - psutil >=5.9.8
    - openpyxl >=3.1.2
    - matplotlib-inline >=0.1.7
    - beautifulsoup4 >=4.12.3
    - selenium >=4.1.3
    - scikit-learn >=1.0.2
    - scipy >=1.7.3
    - seaborn >=0.13.2
    - py3dmol >=2.4.2
    - ipykernel >=6.0.0
    - ipython <9.0.0
    

test:
  imports:
    - bioat
  commands:
    - pip check
    - bioat --help
  requires:
    - pip

about:
  home: https://github.com/hermanzhaozzzz/bioat
  summary: bioat, a python package & command line toolkit for Bioinformatics and data science!
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hermanzhaozzzz
